# Generated by Django 5.0.3 on 2024-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurebook',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
