# Generated by Django 5.0.3 on 2024-03-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_buyer_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
