# Generated by Django 5.0.3 on 2024-03-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_sales_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.AlterField(
            model_name='sales',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.book'),
        ),
    ]
