# Generated by Django 5.0.3 on 2024-03-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
