# Generated by Django 5.0.3 on 2024-03-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_alter_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
