# Generated by Django 5.0.3 on 2024-03-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_requestbook_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='date_of_request',
            field=models.DateTimeField(),
        ),
    ]
