# Generated by Django 5.0.3 on 2024-03-22 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_requestbook_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_list',
            name='threshold',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='vendor_list',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.vendor'),
        ),
    ]
