# Generated by Django 5.0.3 on 2024-03-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_alter_vendor_list_threshold_alter_vendor_list_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='buyer_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
