# Generated by Django 5.0.3 on 2024-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_sales_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_list',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
