# Generated by Django 5.0.3 on 2024-03-29 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0018_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='date_of_request',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
