# Generated by Django 4.2.11 on 2024-04-13 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default='others', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='static/images/book.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='date_of_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 13, 49, 18, 873952, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 13, 49, 18, 873952, tzinfo=datetime.timezone.utc)),
        ),
    ]
